### ISSUE TITLE
Bot hangs and consumes 100% CPU on !fdie

### ISSUE THREAD

**Issue by FastLizard4** [lykoss/lykos#169]
Pretty much what the title says.  When the !fdie command is given in channel, the bot quits from IRC, but the python3 process doesn't terminate, and it instead spins consuming 100% CPU until it is killed externally.

The bot is connected to an InspIRCd 2 server over SSL, and is being run in Python 3.2.3.

I tried doing a `git bisect`, but it seemed that every commit back for several months has this problem.

**Comment by nyuszika7h** [comment]
Please provide debug logs from the point you issue `!fdie` -- does the bot send the `QUIT` message properly and what does the server reply? I've tested on `irc.coldfront.net` though, and it seems to reply with an `ERROR :Closing Link` message as expected, so I'm not sure what may be the problem here.

**Comment by FastLizard4** [comment]
Here are the requested logs:

```
[2015-10-08 10:34:52+0000] <--- receive FastLizard4!fastlizard4@lizardirc/staff/wikipedia.FastLizard4 privmsg (#werewolf, !fdie)
[2015-10-08 10:34:52+0000] #werewolf FastLizard4!fastlizard4@lizardirc/staff/wikipedia.FastLizard4 fdie
[2015-10-08 10:34:52+0000] ---> send 'MODE #werewolf -m'
[2015-10-08 10:34:52+0000] ---> send 'QUIT :Forced quit from FastLizard4'
[2015-10-08 10:34:52+0000] <--- receive None error (Closing link: (mj94@ridley.fastlizard4.org) [Quit: Forced quit from FastLizard4])
```

After this is when it just starts spinning on the CPU.  This time, though, I hit Ctrl-C a second time, and this happened:
```
^C[2015-10-08 10:38:58+0000] ---> send 'MODE #werewolf -m'
[2015-10-08 10:38:58+0000] ---> send 'QUIT :Forced quit from <console>'
Traceback (most recent call last):
  File "/home/mj94/lykos/src/wolfgame.py", line 530, in forced_exit
[2015-10-08 10:38:58+0000] ---> send 'PRIVMSG #werewolf :An error has occurred and has been logged.'
[2015-10-08 10:38:58+0000] closing socket
[2015-10-08 10:38:58+0000] Calling sys.exit()...
[2015-10-08 10:38:58+0000] ---> send 'PRIVMSG #werewolf :An error has occurred and has been logged.'
[2015-10-08 10:38:58+0000] ---> send 'PRIVMSG #werewolf :An error has occurred and has been logged.'
```

When I checked the error log, I found this.  The timestamps don't line up with the debug output I pasted above, but perhaps it's related nonetheless?
```
[2015-10-08 09:43:43+0000] Traceback (most recent call last):
  File "src/wolfgame.py", line 530, in forced_exit
    rest.strip()))
  File "oyoyo/client.py", line 271, in quit
    self.send("QUIT :{0}".format(msg))
  File "oyoyo/client.py", line 163, in send
    self.socket.send(msg + bytes("\r\n", "utf_8"))
  File "/usr/lib/python3.2/ssl.py", line 345, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mj94/lykos/wolfbot.py", line 58, in <module>
    main()
  File "/home/mj94/lykos/wolfbot.py", line 53, in main
    cli.mainLoop()
  File "oyoyo/client.py", line 293, in mainLoop
    if not next(conn):
  File "oyoyo/client.py", line 243, in connect
    yield True
  File "/usr/lib/python3.2/bdb.py", line 48, in trace_dispatch
    return self.dispatch_call(frame, arg)
  File "/usr/lib/python3.2/bdb.py", line 68, in dispatch_call
    def dispatch_call(self, frame, arg):
  File "src/wolfgame.py", line 147, in sighandler
    forced_exit.func(cli, "<console>", botconfig.CHANNEL, "")
  File "src/wolfgame.py", line 532, in forced_exit
    traceback.print_exc()
  File "/usr/lib/python3.2/traceback.py", line 259, in print_exc
    print_exception(etype, value, tb, limit, file, chain)
  File "/usr/lib/python3.2/traceback.py", line 161, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python3.2/traceback.py", line 66, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
  File "/usr/lib/python3.2/traceback.py", line 12, in _print
    file.write(str+terminator)
  File "src/__init__.py", line 142, in write
    self.flush()
  File "src/__init__.py", line 179, in flush
    self.cli.msg(botconfig.CHANNEL, msg)
  File "oyoyo/client.py", line 257, in msg
    self.send("PRIVMSG", user, ":{0}".format(line))
  File "oyoyo/client.py", line 163, in send
    self.socket.send(msg + bytes("\r\n", "utf_8"))
  File "/usr/lib/python3.2/ssl.py", line 345, in send
    v = self._sslobj.write(data)
ssl.SSLError: [Errno 1] _ssl.c:1186: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry
```

**Comment by Vgr255** [comment]
Pull from latest master and see if the issue persists.

**Comment by FastLizard4** [comment]
That seems to have fixed it!  `!fdie` now causes the bot to exit correctly.  Not sure why it seems to only be a problem for me, though.

**Comment by Vgr255** [comment]
Glad that fixed it! I don't know why it did it, but at least now it works :)
