### ISSUE TITLE
Crash on !fgame random with 4 players

### ISSUE THREAD

**Issue by lutoma** [lykoss/lykos#181]
Not sure if this is a known bug or me using the bot wrongly, but this just showed up when testing my PR. I tried again with the master branch and it still was there:

```
        ▬▬▶ | seerwolf (lutoma@shells.fnordserver.eu) has joined #wolfchampionship                                                                  
         ℹ  | Mode #wolfchampionship [+o seerwolf] by ChanServ                                                                                      
     lutoma | !fjoin 1-3                                                                                                                            
  @seerwolf | 1 has started a game of Werewolf. Type "!join" to join. Type "!start" to start the game. Type "!wait" to increase the start wait time.
  @seerwolf | lutoma used fjoin and raised the number of players to 3.                                                                              
     lutoma | !join                                                                                                                                 
  @seerwolf | lutoma has joined the game and raised the number of players to 4.                                                                     
    +lutoma | !fgame ran                                                                                                                            
  @seerwolf | lutoma has changed the game settings successfully.                                                                                    
    +lutoma | !fwait -100                                                                                                                           
  @seerwolf | lutoma forcibly decreased the wait time by 100 seconds.                                                                               
    +lutoma | !start                                                                                                                                
  @seerwolf | An error has occurred and has been logged.                                                                                            
          ↪ | An error has occurred and has been logged.                                                                                            
        ◀▬▬ | seerwolf (lutoma@shells.fnordserver.eu) has quit (Remote host closed the connection)                                                  
```

```
Traceback (most recent call last):
  File "/home/lutoma/lykos/oyoyo/client.py", line 238, in connect
    self.command_handler[command](self, prefix,*fargs)
  File "/home/lutoma/lykos/src/handler.py", line 71, in on_privmsg
    fn.caller(cli, rawnick, chan, h.lstrip())
  File "/home/lutoma/lykos/src/decorators.py", line 129, in caller
    return self.func(*largs)
  File "/home/lutoma/lykos/src/wolfgame.py", line 6843, in start_cmd
    start(cli, nick, chan)
  File "/home/lutoma/lykos/src/wolfgame.py", line 6917, in start
    if event.dispatch(cli, chk_win_conditions, var, villagers):
  File "/home/lutoma/lykos/src/events.py", line 32, in dispatch
    item[1](self, *args)
  File "/home/lutoma/lykos/src/gamemodes.py", line 510, in role_attribution
    addroles["assassin"] = random.randrange(int(len(villagers) ** 1.2 / 8))
  File "/usr/lib/python3.4/random.py", line 186, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()
```

A quick look at gamemodes.py suggests random is 8 players minimum, but for other game modes like alea the bot refuses to start instead of just crashing

**Comment by nyuszika7h** [comment]
This seems to be a problem with `!fgame`, as `var.MIN_PLAYERS` is not set properly. Even if you set that, it will say `No game settings are defined for X player games` instead of `X or more players are required to play`, so that's weird.
