### ISSUE TITLE
Error when lynching wolf

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#188]
On another network, Beancounter, Bagel, Pinf (me), and JD|cloud were `!fjoin`ed to the game. The game was started with `!fstart`. `!revealroles` while in debug mode determined that Beancounter was wolf, so I lynched Beancounter and used `!fnight`. Beancounter was lynched and the game logged an error but didn't end.

The issue seems independent of whether or not a villager is lynched before the wolf and we are on the most recent version of the bot with Python 3.2.3.

```pytb
Traceback (most recent call last):
  File "/home/mj94/lykos/src/decorators.py", line 42, in __call__
    return self.func.__get__(self.instance, self.owner)(*args, **kwargs)
  File "/home/mj94/lykos/src/wolfgame.py", line 3164, in del_player
    ret = not chk_win(cli, end_game)
  File "/home/mj94/lykos/src/wolfgame.py", line 2666, in chk_win
    return chk_win_conditions(lpl, lwolves, lcubs, lrealwolves, lmonsters, ldemoniacs, ltraitors, lpipers, lsuccubi, lentranced, cli, end_game, winner)
  File "/home/mj94/lykos/src/wolfgame.py", line 2761, in chk_win_conditions
    for plr in var.list_players(vroles):
  File "/home/mj94/lykos/src/settings.py", line 455, in list_players
    for x in roles:
  File "/home/mj94/lykos/src/wolfgame.py", line 2760, in <genexpr>
    vroles = (role for role in var.ROLES.keys() if var.ROLES[role] and role not in (var.WOLFTEAM_ROLES | var.TRUE_NEUTRAL_ROLES | var.TEMPLATE_RESTRICTIONS.keys()))
TypeError: unsupported operand type(s) for |: 'frozenset' and 'KeysView'
```

**Comment by Vgr255** [comment]
Fixed in 4e7b8ec
