### ISSUE TITLE
Error adding warnings ≥25

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#242]
I am testing the bot on another IRC channel and encounter the following error whenever I try to add a warning that is equal to or greater than 25 points.

```pytb
Traceback (most recent call last):
  File "/home/calvin/lykos/src/decorators.py", line 40, in __call__
    return self.func(*args, **kwargs)
  File "/home/calvin/lykos/src/decorators.py", line 190, in caller
    return self.func(*largs)
  File "/home/calvin/lykos/src/warnings.py", line 876, in fwarn
    warn_id = add_warning(cli, target, points, nick, reason, notes, expires, sanctions)
  File "/home/calvin/lykos/src/warnings.py", line 162, in add_warning
    if sanc["tempban"][-1] in ("d", "h", "m"):
TypeError: 'int' object is not subscriptable
```

**Comment by skizzerz** [comment]
Already fixed in 1fdd9250d6481152500141b3a3ce082728221b4a
