### ISSUE TITLE
Error setting ban when warning reaches 25 or above

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#245]
``` pytb
Traceback (most recent call last):
  File "/home/calvin/lykos/src/decorators.py", line 40, in __call__
    return self.func(*args, **kwargs)
  File "/home/calvin/lykos/src/decorators.py", line 190, in caller
    return self.func(*largs)
  File "/home/calvin/lykos/src/warnings.py", line 876, in fwarn
    warn_id = add_warning(cli, target, points, nick, reason, notes, expires, sanctions)
  File "/home/calvin/lykos/src/warnings.py", line 195, in add_warning
    (acclist, hmlist) = db.add_warning_sanction(sid, "tempban", sanctions["tempban"])
  File "/home/calvin/lykos/src/db.py", line 693, in add_warning_sanction
    c.execute(sql, (plid, data))
sqlite3.IntegrityError: UNIQUE constraint failed: bantrack.player
```

**Comment by jacob1** [comment]
This is probably an issue related to other errors we already fixed when adding warnings. I couldn't reproduce this anymore, warnings are added just fine and the user gets banned.

If you can find a way to reproduce this again (preferably from a clean database), then comment here or open another issue

**Comment by jacob1** [comment]
Fixed for real now, you were probably messing around and manually unbanned the user or something, then added a warning back. Probably wouldn't happen on a real bot.
